### ISSUE TITLE
consider import/transfer of issues from pacta.interactive.report

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.portfolio.report#2]
We cannot transfer issues directly from a private repo to this public repo, but the [issues in pacta.interactive.report](https://github.com/RMI-PACTA/pacta.portfolio.report/issues) should now be solved here.

**Comment by MonikaFu** [comment]
FYI - I added a label 'in-pacta.portfolio.report' to issues of `pacta.interactive.report` so we can track which issues have been transferred.

**Comment by AlexAxthelm** [comment]
I think I've migrated the important ones over. Marking this one as closed.
