### ISSUE TITLE
get rid of setwd() usage

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.portfolio.report#33]
At
Line 561 in [54b3ff3](https://github.com/RMI-PACTA/pacta.interactive.report/commit/54b3ff30056e398c4dc33890b7194df69910b1f0)
and later...
Line 591 in [54b3ff3](https://github.com/RMI-PACTA/pacta.interactive.report/commit/54b3ff30056e398c4dc33890b7194df69910b1f0)

My memory of the need for this was that getting bookdown/knitr to run from a directory but in a different directory was problematic. I'm hoping maybe things have improved since then (?) and we can find a way to avoid doing this, because it is error prone and problematic for its own reasons.

Along with this, it probably would be good to not run directly in the template directory, but rather copy the template directory to a temp directory, because bookdown/knitr creates files in the template directory (which may not be possible if, for instance, we were to mount the template directories into the docker image into a read-only directory), and if anything goes wrong during the knitting it leaves behind some of these files in the template directory (ostensibly, to facilitate figuring out what went wrong), which is also undesirable in our use case.

For further context... I believe we were always targeting the index.Rmd file, originally with the full path to the index.Rmd, then by setting the directory to where it is and targeting just "index.Rmd". {bookdown} v0.22 brought problems because it changed how it processed the first input argument. We adapted to that here https://github.com/RMI-PACTA/create_interactive_report/pull/445. I think what {bookdown} v0.22 enabled/should have prompted us to do is to simply specify the directory and let it find the index.Rmd inside it, which is probably more in line with what we were going for in the first place.

Migration of https://github.com/RMI-PACTA/pacta.interactive.report/issues/198

**Comment by AlexAxthelm** [comment]
@cjyetman I've had some success passing `normalizePath()`'d paths to the `output_dir`, and `intermediates_dir` arguments of `bookdown::render()`, but the slight trick there is that `normalizePath()` fails if the directory doesn't exist first.

**Comment by cjyetman** [comment]
`dir.create(warn = FALSE)` first to make sure it's there?

**Comment by AlexAxthelm** [comment]
bumping this issue, since I ran into it again while writing #46
