### ISSUE TITLE
prep_emissions_trajectory calls `start_year` from global environment

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.portfolio.report#43]
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/5162593ee62be47ff46c493b93ecd48ff2203b8d/R/prep_emissions_trajectory.R#L47

This function calls `.env$start_year` in a dplyr chain, without it being supplied as an argument to the function.

**Comment by cjyetman** [comment]
nice catch! I'm fairly certain that was unintentionally missed in https://github.com/RMI-PACTA/pacta.interactive.report/pull/132 (done in the predecessor of this repo)

**Comment by AlexAxthelm** [comment]
Am I missing something about inheritence? `start_year` is defined in the calling environment, but doesn't show up in the function's env.

```r
Browse[2]> parent.frame()$start_year
[1] 2022
Browse[2]> start_year
Error in prep_emissions_trajectory(equity_results_portfolio, bonds_results_portfolio,  :
  object 'start_year' not found
```

**Comment by cjyetman** [comment]
so this
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/5162593ee62be47ff46c493b93ecd48ff2203b8d/R/prep_emissions_trajectory.R#L1-L9

should be changed to 
```r
prep_emissions_trajectory <- 
   function(equity_results_portfolio, 
            bonds_results_portfolio, 
            investor_name, 
            portfolio_name, 
            select_scenario_other, 
            select_scenario, 
            twodi_sectors, 
            year_span,
            start_year) { 
```

and this
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/5162593ee62be47ff46c493b93ecd48ff2203b8d/R/create_interactive_report.R#L337-L347

should be changed to
```r
data_emissions <- 
   prep_emissions_trajectory( 
     equity_results_portfolio, 
     bonds_results_portfolio, 
     investor_name, 
     portfolio_name, 
     select_scenario_other, 
     select_scenario, 
     twodi_sectors, 
     year_span,
     start_year
   ) 
```
