### ISSUE TITLE
`export_report_content_variables_json()` is outdated and doesn't calculate all values correctly

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta.portfolio.report#5]
This function calculates numeric values that are later printed within the text of the report. However, the values which are not based on `audit` data are currently resulting in 0's due to incorrect filtering. At the same time, looking at the templates, it seems that none of these are currently in use (Search for 'portfolio_parameters' in `templates.transition.monitor` to see which values are used). Therefore the bug was not discovered yet. I see 2 options for how to proceed:

1. Simplify the `export_report_content_variables_json()` function and return only the values currently in use (my preference, the simpler the code, the better, we can always add variables in case we need them).
2. Fix the filtering so that the (unused) values are calculated correctly.

@cjyetman @jdhoffa @AlexAxthelm curious to hear your thoughts.

**Comment by cjyetman** [comment]
Option 1 makes sense to me, but maybe the analysts would have a better sense of if those variables are likely to be used again

**Comment by MonikaFu** [comment]
Thanks @cjyetman! Honestly, I don't think that there will be significant changes in the report text before the end of PACTA 2.0 exercise after which the changes might be so significant that this function potentially becomes obsolete. I also don't think that the analysts are aware of these parameters being calculated at the moment and I'm not sure if I want to make them aware. Explaining it might take more time than it's worth. And we can always `git blame` right? But happy to run it over the analysts if it's considered necessary. @AlexAxthelm what is your view? I guess you are the deciding voice here.

**Comment by MonikaFu** [comment]
`portfolio parameters` currently in use within templates are:

```
portfolio_parameters$InvestorName
portfolio_parameters$PortfolioName
portfolio_parameters$total_portfolio_value_curr
portfolio_parameters$total_portfolio_percentage_equity
portfolio_parameters$total_portfolio_percentage_bonds
portfolio_parameters$total_portfolio_percentage_coverage
```

`portfolio_parameters` which are calculated by `export_report_content_variables_json()`:

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/4dd98f755482b25b6b42b7d12a936e6db0946614/R/export_report_content_variables_json.R#L128-L150

**Comment by AlexAxthelm** [comment]
Option 1 seems like the obvious choice here. Let's simplify the json export. Thanks for investigating the current usage, @MonikaFu
