### ISSUE TITLE
future tech bar chart might show least important companies instead of most important

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.portfolio.report#82]
from user feedback (https://docs.google.com/spreadsheets/d/1tgeV4IsmqVZWExFcDKpjcmdqsG28VgcilPcM-OP5OW8/edit?gid=1322498032#gid=1322498032&range=13:13)
> Why are all weights equal to 0%? Could it be that instead of the biggest companies in the portfolio the smallest were taken?

from @Antoine-Lalechere 
> I think in the company bar chart there is a mistake in the company we show. Companies order should be reversed (Honda be shown as first one of those fifteen companies as it gets the larger weight).
> <img width="664" alt="thumbnail_image001" src="https://github.com/RMI-PACTA/pacta.portfolio.report/assets/1708872/865623f6-4d90-4b1d-989e-2802a6aa95c0">

[AB#11177](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11177)

**Comment by cjyetman** [comment]
possibly this
https://github.com/RMI-PACTA/pacta.portfolio.report/blob/9a24a10c80bfb283cc15fe2c8afc744f3f36c67a/R/prep_key_bars_company.R#L61

should be 
``` r
arrange(dplyr::desc(.data$port_weight), .by_group = TRUE) %>% 
```
?

**Comment by Antoine-Lalechere** [comment]
Yes and same one L31
