### ISSUE TITLE
Real Estate file handline cannot handle actual `reports.json`

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.portfolio.report#97]
In the PROD `reports.json` files for Real Estate Reports for PA2024CH, the JSON array contains an extra (empty) array:

Expected:
```json
  "reports": {
    "executive_summary": [
      {
        "portfolio_type": "mortgage",
        "de": {
```

Actual:
```json
  "reports": {
    "executive_summary": [
      [],
      {
        "portfolio_type": "mortgage",
        "de": {
```

The current code iterates over array elements, and chokes on the unkeyed, empty array.

**Comment by AlexAxthelm** [comment]
cc @jdhoffa

**Comment by jdhoffa** [comment]
Tracked on ADO https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/12082
